# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Toma las capturas de pantalla de la app y las descarga a la computadora"
  lane :screenshots do
    gradle(task: "assembleDebug assembleDebugAndroidTest")
        capture_android_screenshots(
          locales: ["es-ES"],
          clear_previous_screenshots: true,
          use_tests_in_classes: ["org.universalworldtechnologyec.cedulamovil.ScreenshotTest"],
          app_apk_path: "app/build/outputs/apk/debug/app-debug.apk",
          tests_apk_path: "app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk"
        )
  end
end
